spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/transaction_learn?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.hblolj.springtransactionlearn.dataobject
